### ISSUE TITLE
How can i run it on micropython(ESP32)

### ISSUE THREAD

**Issue by XuBovey** [doudz/zigpy-zigate#12]
Hi,
i want to try zigpy-zigate on esp32, cloud u help me something. what should i do to start it.
thanks!

**Comment by doudz** [comment]
I don't think it's possible
zigpy-zigate and zigpy use many lib unavailable on micropython like serial_asyncio for example

Additionnally zigpy-zigate is a extension for zigpy to support zigate and cannot be use standalone.
zigpy is (as far as I know) only use by home assistant

**Comment by doudz** [comment]
why would you run on esp32 ?

**Comment by XuBovey** [comment]
thanks for your replay. It's just a idea, because I just have the zigbee and esp32 module.
