### ISSUE TITLE
upcoming changes in zigpy

### ISSUE THREAD

**Issue by Adminiuga** [doudz/zigpy-zigate#5]
Just wanted to give a heads up about changes in the zigpy library which would require changes on your side too.
See https://github.com/zigpy/zigpy/pull/223

Shouldn't be too bad and actually should make your code a bit simpler.  The gist of change:
- `request()`/`broadcast()`  just need to send the data out and wait for send confirmation, returning a tuple of `(status, message)` , shouldn't raise any `DeliveryError` exceptions and leave it to zigpy. If you raise an exception here, zigpy will allow it to bubble up.
- for incoming messages, just pass them through to zigpy, zigpy will handle deserialization and request/reply session tracking

**Comment by Adminiuga** [comment]
Here's a mock of changes for Zigate. I don't have an actual dongle so can't confirm the validity. I assume https://github.com/Adminiuga/zigpy-zigate/blob/1e8b1efe3b29529038e497b83a5fd6038d27e80f/zigpy_zigate/zigbee/application.py#L111 is called for both successful and unsuccessful transmissions.

https://github.com/Adminiuga/zigpy-zigate/tree/zigpy-090-sync

**Comment by doudz** [comment]
Thanks.
I saw that you remove the _zigate_seq variable but did you see that zigate handle the sequence number by itself ? since zigpy does it too, we need to translate the zigate sequence number to zigpy sequence number , or am I wrong ?

**Comment by Adminiuga** [comment]
I removed it cause I didn't see where it was used, but I could be wrong. 
`_zigate_seq` is set in https://github.com/doudz/zigpy-zigate/blob/6136fc1d7a33b55de27b08bbd13c36db22b0dbb2/zigpy_zigate/zigbee/application.py#L162 but where is it read/accessed afterwards (except exception handling)?

is `v[1] on line 162 the `message_tag` number you will be getting `msg == 0x8702  # APS Data confirm fail` later?

**Comment by Adminiuga** [comment]
about the sequence number, with this change I don't think radios really care about the sequence number they get from zigpy at all, as in this approach radios are "stateless" in the sense they don't have to track/correlate requests with replies (before, the sequence # was used to match incoming data TSN to previously sent requests).

Radio just needs to send the "payload" to destination and return a tuple `(0, "message sent successfuly")` if it gets the APS Data confirm or `(1, "error message")` if it does not get APS data confirm or gets an error sending. and usually it is radio implementation specific to match the outgoing request with APS data confirm. eg in Deconz just uses next sequence number and when it receives the APS_DATA_CONFIRM with the same number it matches the confirmation with the request and signals back to zigpy whether the transmission was successful or not.
Hope this makes sense.

**Comment by doudz** [comment]
Thanks for details.
And you're right, zigate_seq wasn't used, I removed the sequence number during tests and just forgot to restore it.
Since it's no more needed, it doesn't matter

**Comment by doudz** [comment]
I took a deeper look at your mock code and I have questions :

https://github.com/Adminiuga/zigpy-zigate/blob/1e8b1efe3b29529038e497b83a5fd6038d27e80f/zigpy_zigate/zigbee/application.py#L131-L143
We don't need to wait for ack because it's already done by raw_aps_data_request, in previous version we only wait when we expect a reply


What's the purpose of 
```
req_id = self.get_sequence()
send_fut = asyncio.Future()
self._pending[req_id] = send_fut
```
is it only used in case of failure ? (what you are currently suggesting)
self._pending is almost unused

**Comment by doudz** [comment]
The "problem" is that ZiGate only send msg 8702 Frame failure in case of failure, there's no special ack  is everything is fine

**Comment by doudz** [comment]
Since ZiGate doesn't provide a way to handle ack, I will remove this part of code and APS DATA Failure will only be a error message in the log (we can't use it as status in request())

**Comment by doudz** [comment]
https://github.com/fairecasoimeme/ZiGate/issues/239

**Comment by Adminiuga** [comment]
>What's the purpose of
>```
>req_id = self.get_sequence()
>send_fut = asyncio.Future()
>self._pending[req_id] = send_fut
>```

Original purpose was to track Req and ACK/NAK using radios own sequence # 

So when you send request in https://github.com/Adminiuga/zigpy-zigate/blob/1e8b1efe3b29529038e497b83a5fd6038d27e80f/zigpy_zigate/zigbee/application.py#L131, the `v[0]` would contain `0` for successfully sent messages (messages we got ACK for) and in a case of failure it would contain `!= 0` and you also get `msg == 0x8702`  callback?

**Comment by Adminiuga** [comment]
in other words, is https://github.com/Adminiuga/zigpy-zigate/blob/1e8b1efe3b29529038e497b83a5fd6038d27e80f/zigpy_zigate/zigbee/application.py#L131 waiting till we know the result of operation, eg far end ACKed the transmission or we get NAK from the network? or does it return just indicating that data was en-queued for sending by the radio?

**Comment by doudz** [comment]
v[0] is the status returned by ZiGate about the sent
0 = Success	
1 = Incorrect parameters	
2 = Unhandled command	
3 = Command failed	
4 = Busy (Node is carrying out a lengthy operation and is currently unable to handle the incoming command)
5 = Stack already started (no new configuration accepted)	
128 – 244 = Failed (ZigBee event codes)

But in case of success (v[0] == 0) if the end device doesn't receive the request for some reason (device unavailable, out of range, ...) , we will get a 8702 message.

I opened issue https://github.com/fairecasoimeme/ZiGate/issues/239 to ask ZiGate improvement to have a ack message even on success, not only on failure

**Comment by Adminiuga** [comment]
> But in case of success (v[0] == 0) if the end device doesn't receive the request for some reason (device unavailable, out of range, ...) , we will get a 8702 message.

So essentially L131 just tells that data was en-queued and we only get failure notification. IMO for now don't use the `send_future` and just return whatever `v[0]` dictates for. When https://github.com/fairecasoimeme/ZiGate/issues/239 gets implemented, bring `send_future` back and return upon 0x8702 or successful ACK.

**Comment by doudz** [comment]
Ok thanks
so I think I'm ready now.
How can I check ? is the current zha component compatible with zigpy 0.9.0 ?

**Comment by Adminiuga** [comment]
update `manifest.json` in `homeassistant/components/zha` to use `zigpy==0.9.0` and try with updated zigate.

**Comment by doudz** [comment]
not sure why, I get the following
```
2019-09-24 06:17:26 ERROR (MainThread) [zigpy_zigate.api] Exception running handler
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/zigpy_zigate/api.py", line 155, in handle_callback
    handler(*args)
  File "/srv/homeassistant/lib/python3.7/site-packages/zigpy_zigate/zigbee/application.py", line 110, in zigate_callback_handler
    response[3], response[4], response[-1])
TypeError: handle_message() missing 3 required positional arguments: 'tsn', 'command_id', and 'args'
```

**Comment by doudz** [comment]
@Adminiuga There's a problem
```
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/zigpy_zigate/api.py", line 155, in handle_callback
    handler(*args)
  File "/srv/homeassistant/lib/python3.7/site-packages/zigpy_zigate/zigbee/application.py", line 110, in zigate_callback_handler
    response[3], response[4], response[-1])
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/zha/core/patches.py", line 22, in handle_message
    return sender.handle_message(profile, cluster, src_ep, dst_ep, message)
  File "/srv/homeassistant/lib/python3.7/site-packages/zigpy/device.py", line 206, in handle_message
    tsn, command_id, is_reply, args = self.deserialize(src_ep, cluster, message)
  File "/srv/homeassistant/lib/python3.7/site-packages/zigpy/device.py", line 196, in deserialize
    return self.endpoints[endpoint_id].deserialize(cluster_id, data)
  File "/srv/homeassistant/lib/python3.7/site-packages/zigpy/endpoint.py", line 173, in deserialize
    return cluster.deserialize(data)
TypeError: deserialize() missing 4 required positional arguments: 'frame_type', 'is_reply', 'command_id', and 'data'
2019-09-24 20:21:45 ERROR (MainThread) [zigpy_zigate.api] Exception running handler
```

**Comment by Adminiuga** [comment]
Hrm, the traceback is confusing. Per traceback the problem is in zigpy deserialize calling in endpoint `return cluster.deserialize(data)`, but signature in https://github.com/zigpy/zigpy/blob/3009e4397fbf2e3f648a4fce1202d5a2fbdd34ab/zigpy/zcl/__init__.py#L80 is correct.

Ah, one thing I forgot to mention, install latest `zha-device-handlers` too, because xiaomi quirk is hooking into deserialize. I bet that what it is.

**Comment by doudz** [comment]
Could it be in zhaquirks/xiaomi/__init__.py ?

**Comment by Adminiuga** [comment]
Yes, there was a zha-device-handlers release associated with this zigpy update https://github.com/dmulcahey/zha-device-handlers/pull/147 in should be in `zha-quirks==0.0.23` https://github.com/dmulcahey/zha-device-handlers/tree/0.0.23

**Comment by doudz** [comment]
hum why my deps are still using 0.0.22 ?!
```
(homeassistant) homeassistant@raspberrypi:/srv/homeassistant $ pip3 list |grep zha
zha-quirks               0.0.22
```

**Comment by doudz** [comment]
Everything is fine

**Comment by Adminiuga** [comment]
HA dev is already using new version https://github.com/home-assistant/home-assistant/pull/26746. After you publish the new version (you may want to put minimum zigpy requirement of >=0.9.0) to PyPi, bump zigate in manifest.json and create a PR to HA repo.
